// Learn cc.Class:
//  - [Chinese] https://docs.cocos.com/creator/manual/zh/scripting/class.html
//  - [English] http://docs.cocos2d-x.org/creator/manual/en/scripting/class.html
// Learn Attribute:
//  - [Chinese] https://docs.cocos.com/creator/manual/zh/scripting/reference/attributes.html
//  - [English] http://docs.cocos2d-x.org/creator/manual/en/scripting/reference/attributes.html
// Learn life-cycle callbacks:
//  - [Chinese] https://docs.cocos.com/creator/manual/zh/scripting/life-cycle-callbacks.html
//  - [English] https://www.cocos2d-x.org/docs/creator/manual/en/scripting/life-cycle-callbacks.html

cc.Class({
    extends: cc.Component,

    properties: {
        // foo: {
        //     // ATTRIBUTES:
        //     default: null,        // The default value will be used only when the component attaching
        //                           // to a node for the first time
        //     type: cc.SpriteFrame, // optional, default is typeof default
        //     serializable: true,   // optional, default is true
        // },
        // bar: {
        //     get () {
        //         return this._bar;
        //     },
        //     set (value) {
        //         this._bar = value;
        //     }
        // },
        gameRuning:{
            default:false,
            serializable:true,
        },

        gameSpeed:{
            default:0,
            serializable:true,
        },

        gameOver:{
            default:false,
            serializable:true,
        }
    },

    // LIFE-CYCLE CALLBACKS:

    onLoad () {
        //开碰撞
        let manager = cc.director.getCollisionManager();
        manager.enabled = true;

        GLOBAL_DATA.GAME = this;
    },

    start () {

    },

    onSetGameRunOrPause(){
        this.gameRuning =!this.gameRuning;
        console.log( this.gameRuning );
    },
    setGlobalGameRun(isRun){
        this.gameRuning = isRun;
    },

    setGlobalSpeed(speed){
       this.gameSpeed = speed;
    },
    onGoMatching: function () {
        // 切换到场景
        cc.director.loadScene("matching", () => {
            console.log('进入匹配场景');
        });
    },

    // update (dt) {},
});
